name: Python Unit Test Check

on:
  push:
    branches:
      - main 
  pull_request:
    branches: [ main ]

jobs:
  python-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
        with:
          submodules: recursive
      - name: Set up system
        run: pip install -r requirements.txt
      - name: Run Python Unit Tests
        run: python3 scripts/test_python_source.py